version: '3.8'

services:
  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
  web:
    build: .
    command: python app.py
    ports:
      - 8050:8050